version: '3'
services:
  picx:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/db
    networks:
      - picx
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017"
    networks:
      - picx

networks:
  picx:
    driver: bridge
